package com.company.enums;

public enum AdminStatus {
    ENTER_CATEGORY_NAME_FOR_ADD,
    ENTER_CATEGORY_NAME_FOR_EDIT,
    ENTER_PRODUCT_NAME_FOR_ADD,
    ENTER_PRODUCT_PRICE_FOR_ADD,
    ENTER_PRODUCT_DESCRITION_FOR_ADD,
    SEND_PRODUCT_IMAGE_FOR_ADD,
    SHARE_ADVERT,
}
